<?php
return array (
  11 => 
  array (
    'id' => '11',
    'catid' => '15',
    'typeid' => '0',
    'title' => '强化统筹 注重实效 扎实开展流动人口关怀关爱活动',
    'style' => '',
    'thumb' => '',
    'keywords' => '流动人口 实效',
    'description' => '为贯彻落实国家卫生计生委《关于做好元旦春节期间流动人口“关怀关爱”活动的通知》相关要求，重庆市卫生计生委高度重视，',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=15&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458009415',
    'updatetime' => '1458009488',
    'hitsid' => 'c-1-11',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  61 => 
  array (
    'id' => '61',
    'catid' => '15',
    'typeid' => '0',
    'title' => '善用契机  抓好计生药具宣传',
    'style' => '',
    'thumb' => 'http://www.cqyxjy.com/uploadfile/2016/0614/20160614104448658.png',
    'keywords' => '药具 契机',
    'description' => '  为深入宣传计生免费药具政策，让国家提供的免费避孕药具更方便的惠及广大育龄群众。1月25日，九龙坡区公共卫生和计划生育管理服务中心   ',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=15&id=61',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1465872231',
    'updatetime' => '1465872312',
    'hitsid' => 'c-1-61',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  60 => 
  array (
    'id' => '60',
    'catid' => '15',
    'typeid' => '0',
    'title' => '区公共卫生和计划生育管理服务中心“两学一做”专题党课',
    'style' => '',
    'thumb' => 'http://www.cqyxjy.com/uploadfile/2016/0614/20160614104330634.png',
    'keywords' => '党课 公共卫生 服务中心',
    'description' => '全面推进  从严治党---区公共卫生和计划生育管理服务中心两学一做专题党课  为深入学习、全面推进中共中央印发的《中国共产党廉洁自律   ',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=15&id=60',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1465872107',
    'updatetime' => '1465872230',
    'hitsid' => 'c-1-60',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  59 => 
  array (
    'id' => '59',
    'catid' => '15',
    'typeid' => '0',
    'title' => '领导重视  计生药具宣传深入镇街',
    'style' => '',
    'thumb' => 'http://www.cqyxjy.com/uploadfile/2016/0614/20160614104140393.png',
    'keywords' => '药具',
    'description' => '  为落实国家惠民政策，让国家提供的免费避孕药具更好的惠及广大育龄群众，区公共卫生和计生生育管理服务中心主任严永勤非常重视计生药具   ',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=15&id=59',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1465872057',
    'updatetime' => '1465872106',
    'hitsid' => 'c-1-59',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  58 => 
  array (
    'id' => '58',
    'catid' => '15',
    'typeid' => '0',
    'title' => '九龙坡区开展全区计生药具业务知识培训',
    'style' => '',
    'thumb' => 'http://www.cqyxjy.com/uploadfile/2016/0614/20160614104042885.png',
    'keywords' => '九龙坡区 药具 全区',
    'description' => '  为进一步提高我区计划生育药具管理人员的业务素质，规范计划生育药具管理与服务工作，适应药具管理工作的新要求， 4月22日和4月26日，   ',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=15&id=58',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1465871964',
    'updatetime' => '1465872055',
    'hitsid' => 'c-1-58',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  57 => 
  array (
    'id' => '57',
    'catid' => '15',
    'typeid' => '0',
    'title' => '基层卫生机构2016年绩效考核指标研讨会简报',
    'style' => '',
    'thumb' => '',
    'keywords' => '卫生机构 简报 绩效',
    'description' => '优化绩效考核方案，提升绩效管理内涵  2016年3月16日下午，区卫生计生委人事科教科组织召开了九龙坡区公共卫生和基层医疗卫生事业单位绩   ',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=15&id=57',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1465871875',
    'updatetime' => '1465871963',
    'hitsid' => 'c-1-57',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  56 => 
  array (
    'id' => '56',
    'catid' => '15',
    'typeid' => '0',
    'title' => '生专业技术资格考试报名现场确认工作',
    'style' => '',
    'thumb' => '',
    'keywords' => '资格考试 专业 技术',
    'description' => '转变服务观念 强化服务意识&mdash;&mdash;区公共卫生和计划生育管理服务中心完成2016年全区护士执业资格考试、卫生专业技术资格考试报名现场确认工作   ',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=15&id=56',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1465871817',
    'updatetime' => '1465871873',
    'hitsid' => 'c-1-56',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  55 => 
  array (
    'id' => '55',
    'catid' => '15',
    'typeid' => '0',
    'title' => '九龙坡区继教委召开继续医学教育工作会',
    'style' => '',
    'thumb' => 'http://www.cqyxjy.com/uploadfile/2016/0614/20160614103440687.png',
    'keywords' => '九龙坡区 医学教育 工作会',
    'description' => '深入贯彻继续医学教育政策 扎实推进继续医学教育工作&mdash;&mdash;九龙坡区继教委召开继续医学教育工作会  为进一步加强继续医学教育工作，提升辖   ',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=15&id=55',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1465871588',
    'updatetime' => '1465871815',
    'hitsid' => 'c-1-55',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>