<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '12',
    'typeid' => '0',
    'title' => '重庆市九龙坡区公共卫生和计划生育管理服务中心职责',
    'style' => '',
    'thumb' => '',
    'keywords' => '单位 简介',
    'description' => '一、机构性质及类别重庆市九龙坡区公共卫生和计划生育管理服务中心 为区卫生计生委所属正科级事业单位，经费渠道为区财政全额拨款，机构类   ',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=12&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1453709447',
    'updatetime' => '1453709489',
    'hitsid' => 'c-1-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  25 => 
  array (
    'id' => '25',
    'catid' => '14',
    'typeid' => '0',
    'title' => '九龙坡区公共卫生和计划生育管理服务中心',
    'style' => '',
    'thumb' => '',
    'keywords' => '九龙坡区 公共卫生 服务中心',
    'description' => '九龙坡区公共卫生和计划生育管理服务中心关于相关科室职能职责   (一）公共卫生管理科  职能职责：负责贯彻落实公共卫生管理服务相关   ',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=14&id=25',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458115474',
    'updatetime' => '1458115552',
    'hitsid' => 'c-1-25',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>