<?php
return array (
  14 => 
  array (
    'id' => '14',
    'catid' => '20',
    'typeid' => '0',
    'title' => '继续医学教育规定(试行)',
    'style' => '',
    'thumb' => '',
    'keywords' => '医学教育',
    'description' => '    第一章 总则第一条 为实施科教兴国战略，适应社会主义卫生事业发展需要，国家对卫生技术人员实行继续医学教育制度。依据《教育法   ',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=20&id=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458010313',
    'updatetime' => '1458010362',
    'hitsid' => 'c-1-14',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  15 => 
  array (
    'id' => '15',
    'catid' => '20',
    'typeid' => '0',
    'title' => '全国继续医学教育 “十五”计划',
    'style' => '',
    'thumb' => '',
    'keywords' => '医学教育 全国',
    'description' => '    21世纪是知识经济时代，是经济与社会加速发展、生命科学将取得重大突破的时代。实施继续医学教育是提高我国卫生队伍整体素质的重要   ',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=20&id=15',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458010457',
    'updatetime' => '1458010501',
    'hitsid' => 'c-1-15',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  16 => 
  array (
    'id' => '16',
    'catid' => '20',
    'typeid' => '0',
    'title' => '重庆市继续医学教育项目管理办法',
    'style' => '',
    'thumb' => '',
    'keywords' => '重庆市 医学教育 管理办法',
    'description' => '    为加强我市继续医学教育工作，不断提高卫生计生技术人员的专业素质和服务水平，根据《重庆市专业技术人员继续教育条例》和《重庆市   ',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=20&id=16',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458010716',
    'updatetime' => '1458010766',
    'hitsid' => 'c-1-16',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  17 => 
  array (
    'id' => '17',
    'catid' => '20',
    'typeid' => '0',
    'title' => '重庆市继续医学教育学分管理办法专技人员',
    'style' => '',
    'thumb' => 'http://jxjy.90h. /uploadfile/2016/0315/20160315112849405.png',
    'keywords' => '重庆市 医学教育 学分',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=20&id=17',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1458012484',
    'updatetime' => '1458012534',
    'hitsid' => 'c-1-17',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  68 => 
  array (
    'id' => '68',
    'catid' => '20',
    'typeid' => '0',
    'title' => '重庆市九龙坡区卫生和计划生育委员会 关于进一步规范继续',
    'style' => '',
    'thumb' => '',
    'keywords' => '九龙坡区 重庆市 委员会',
    'description' => '为进一步加强继续医学教育工作，促进继续医学教育的持续健康发展，根据《重庆市专业技术人员继续教育条例》和《重庆市卫生和计划生育委员会关于进一步加强我市继续医学教育工作的意见',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=20&id=68',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1488334425',
    'updatetime' => '1488334836',
    'hitsid' => 'c-1-68',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  69 => 
  array (
    'id' => '69',
    'catid' => '20',
    'typeid' => '0',
    'title' => '重庆市卫生和计划生育委员会 关于加强和改进继续医学教育',
    'style' => '',
    'thumb' => '',
    'keywords' => '重庆市 委员会 文件',
    'description' => '各区县（自治县）卫生计生委、两江新区社发局、万盛经开区卫生计生局，各委属（代管）单位，大型企事业单位职工医院：  为深入贯彻中共中   ',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=20&id=69',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1493860201',
    'updatetime' => '1493860432',
    'hitsid' => 'c-1-69',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>