<?php
return array (
  45 => 
  array (
    'id' => '45',
    'catid' => '21',
    'typeid' => '0',
    'title' => '联系方式',
    'style' => '',
    'thumb' => '',
    'keywords' => '联系方式',
    'description' => '联系我们：重庆市九龙坡区公共卫生和计划生育管理服务中心地址：电话：邮编公司主页：',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=21&id=45',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1465268066',
    'updatetime' => '1465268473',
    'hitsid' => 'c-1-45',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  66 => 
  array (
    'id' => '66',
    'catid' => '31',
    'typeid' => '0',
    'title' => '如何在IE中中直接查看PDF文件',
    'style' => '',
    'thumb' => '',
    'keywords' => '文件',
    'description' => '　',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=29&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1466046607',
    'updatetime' => '1466046638',
    'hitsid' => 'c-1-66',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  67 => 
  array (
    'id' => '67',
    'catid' => '31',
    'typeid' => '0',
    'title' => '如何参加学习',
    'style' => '',
    'thumb' => '',
    'keywords' => '如何参加学习',
    'description' => '　',
    'posids' => '0',
    'url' => 'http://www.cqyxjy.com/index.php?m=content&c=index&a=show&catid=29&id=65',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'admin',
    'inputtime' => '1466046654',
    'updatetime' => '1466046667',
    'hitsid' => 'c-1-67',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>