<?php
return array (
  19 => 
  array (
    'catid' => '19',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '19,20,21,22,23,24,25,26,27',
    'catname' => '杏坛镇',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'catdir' => 'txz',
    'url' => 'http://lvyou.loc/index.php?m=content&c=index&a=lists&catid=19',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '19',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xingtanzhen',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  20 => 
  array (
    'catid' => '20',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '19',
    'arrparentid' => '0,19',
    'child' => '0',
    'arrchildid' => '20',
    'catname' => '地图列表',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'txz/',
    'catdir' => 'dituliebiao',
    'url' => 'http://lvyou.loc/index.php?m=content&c=index&a=lists&catid=20',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '20',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'dituliebiao',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  21 => 
  array (
    'catid' => '21',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '19',
    'arrparentid' => '0,19',
    'child' => '1',
    'arrchildid' => '21,22,23,24,25,26,27',
    'catname' => '下级景区',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'txz/',
    'catdir' => 'xiajijingqu',
    'url' => 'http://lvyou.loc/index.php?m=content&c=index&a=lists&catid=21',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '21',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xiajijingqu',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  22 => 
  array (
    'catid' => '22',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '21',
    'arrparentid' => '0,19,21',
    'child' => '0',
    'arrchildid' => '22',
    'catname' => '缝简水乡',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'txz/xiajijingqu/',
    'catdir' => 'fengjianshuixiang',
    'url' => 'http://lvyou.loc/index.php?m=content&c=index&a=lists&catid=22',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '22',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'fengjianshuixiang',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  23 => 
  array (
    'catid' => '23',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '21',
    'arrparentid' => '0,19,21',
    'child' => '0',
    'arrchildid' => '23',
    'catname' => '北水村',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'txz/xiajijingqu/',
    'catdir' => 'beishuicun',
    'url' => 'http://lvyou.loc/index.php?m=content&c=index&a=lists&catid=23',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '23',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'beishuicun',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  24 => 
  array (
    'catid' => '24',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '21',
    'arrparentid' => '0,19,21',
    'child' => '0',
    'arrchildid' => '24',
    'catname' => '古郎村',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'txz/xiajijingqu/',
    'catdir' => 'gulangcun',
    'url' => 'http://lvyou.loc/index.php?m=content&c=index&a=lists&catid=24',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '24',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'gulangcun',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  25 => 
  array (
    'catid' => '25',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '21',
    'arrparentid' => '0,19,21',
    'child' => '0',
    'arrchildid' => '25',
    'catname' => '龙潭村',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'txz/xiajijingqu/',
    'catdir' => 'longtancun',
    'url' => 'http://lvyou.loc/index.php?m=content&c=index&a=lists&catid=25',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '25',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'longtancun',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  26 => 
  array (
    'catid' => '26',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '21',
    'arrparentid' => '0,19,21',
    'child' => '0',
    'arrchildid' => '26',
    'catname' => '马东村',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'txz/xiajijingqu/',
    'catdir' => 'madongcun',
    'url' => 'http://lvyou.loc/index.php?m=content&c=index&a=lists&catid=26',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '26',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'madongcun',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
  27 => 
  array (
    'catid' => '27',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '21',
    'arrparentid' => '0,19,21',
    'child' => '0',
    'arrchildid' => '27',
    'catname' => '右摊村',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => 'txz/xiajijingqu/',
    'catdir' => 'youtancun',
    'url' => 'http://lvyou.loc/index.php?m=content&c=index&a=lists&catid=27',
    'items' => '0',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"0","content_ishtml":"0","create_to_html_root":"0","template_list":"default","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"6","show_ruleid":"16"}',
    'listorder' => '27',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'youtancun',
    'usable_type' => '',
    'create_to_html_root' => '0',
    'ishtml' => '0',
    'content_ishtml' => '0',
    'category_ruleid' => '6',
    'show_ruleid' => '16',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>